-- ============================================================
-- DOC_APPOINTER FULL DATABASE SCHEMA
-- ============================================================

-- =========================
-- USERS
-- =========================
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),
    role VARCHAR2(50)
);

-- =========================
-- ADMIN
-- =========================
CREATE TABLE admin (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    role VARCHAR2(50),
    branch_id NUMBER,
    CONSTRAINT fk_admin_user FOREIGN KEY(user_id) REFERENCES users(user_id)
);

-- =========================
-- PATIENT
-- =========================
CREATE TABLE patient (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    dob DATE,
    gender VARCHAR2(10),
    occupation VARCHAR2(100),
    blood_type VARCHAR2(5),
    marital_status VARCHAR2(20),
    address VARCHAR2(200),
    CONSTRAINT fk_patient_user FOREIGN KEY(user_id) REFERENCES users(user_id)
);

-- =========================
-- DOCTOR
-- =========================
CREATE TABLE doctor (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    admin_id NUMBER,
    license_number VARCHAR2(50),
    degrees VARCHAR2(100),
    experience_years NUMBER,
    available_days_times VARCHAR2(200),
    dept_id NUMBER,
    branch_id NUMBER,
    CONSTRAINT fk_doctor_user FOREIGN KEY(user_id) REFERENCES users(user_id),
    CONSTRAINT fk_doctor_admin FOREIGN KEY(admin_id) REFERENCES admin(admin_id)
);

-- =========================
-- DEPARTMENTS
-- =========================
CREATE TABLE departments (
    dept_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER NOT NULL,
    name VARCHAR2(100),
    description VARCHAR2(200),
    CONSTRAINT fk_dept_admin FOREIGN KEY(admin_id) REFERENCES admin(admin_id)
);

-- =========================
-- SPECIALIZATION
-- =========================
CREATE TABLE specialization (
    specialization_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER NOT NULL,
    name VARCHAR2(100),
    description VARCHAR2(200),
    CONSTRAINT fk_spec_admin FOREIGN KEY(admin_id) REFERENCES admin(admin_id)
);

-- =========================
-- EMERGENCY_CONTACTS
-- =========================
CREATE TABLE emergency_contacts (
    contact_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    contact_no VARCHAR2(20),
    name VARCHAR2(100),
    relation VARCHAR2(50),
    contact_address VARCHAR2(200),
    CONSTRAINT fk_emergency_patient FOREIGN KEY(patient_id) REFERENCES patient(patient_id)
);

-- =========================
-- TIME_SLOTS
-- =========================
CREATE TABLE time_slots (
    slot_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id_last NUMBER,
    start_time DATE,
    end_time DATE,
    status VARCHAR2(20),
    last_edited_at DATE,
    type_id NUMBER
);

-- =========================
-- BEDS
-- =========================
CREATE TABLE beds (
    bed_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER,
    room_number VARCHAR2(20),
    ward_number VARCHAR2(20),
    type VARCHAR2(50),
    status VARCHAR2(20)
);

-- =========================
-- DOC_SPECIALIZATION
-- =========================
CREATE TABLE doc_specialization (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id NUMBER NOT NULL,
    specialization_id NUMBER NOT NULL,
    CONSTRAINT fk_doc_spec_doctor FOREIGN KEY(doctor_id) REFERENCES doctor(doctor_id),
    CONSTRAINT fk_doc_spec_specialization FOREIGN KEY(specialization_id) REFERENCES specialization(specialization_id)
);

-- =========================
-- BILLS
-- =========================
CREATE TABLE bills (
    bill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER,
    appointment_id NUMBER,
    total_amount NUMBER,
    status VARCHAR2(20),
    issue_date DATE
);

-- =========================
-- BILL_RECEIPT
-- =========================
CREATE TABLE bill_receipt (
    receipt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(200),
    paying_date DATE,
    amount NUMBER,
    paying_method VARCHAR2(50)
);

-- =========================
-- TESTS
-- =========================
CREATE TABLE tests (
    test_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER,
    test_name VARCHAR2(100),
    test_hours NUMBER,
    technician_id NUMBER
);

-- =========================
-- MEDICAL_TECHNICIAN
-- =========================
CREATE TABLE medical_technician (
    tech_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    admin_id NUMBER,
    degrees VARCHAR2(100),
    experience_years NUMBER,
    dept_id NUMBER,
    branch_id NUMBER,
    CONSTRAINT fk_tech_user FOREIGN KEY(user_id) REFERENCES users(user_id)
);

-- =========================
-- DOCTORS_APPOINTMENTS
-- =========================
CREATE TABLE doctors_appointments (
    appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    appointment_date DATE,
    time_slot_id NUMBER,
    status VARCHAR2(20),
    type VARCHAR2(50),
    CONSTRAINT fk_doctor_appointment_patient FOREIGN KEY(patient_id) REFERENCES patient(patient_id),
    CONSTRAINT fk_doctor_appointment_doctor FOREIGN KEY(doctor_id) REFERENCES doctor(doctor_id)
);

-- =========================
-- LAB_TEST_APPOINTMENTS
-- =========================
CREATE TABLE lab_test_appointments (
    lab_appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    reference VARCHAR2(100),
    doctor_id NUMBER,
    time_slot_id NUMBER,
    test_id NUMBER,
    test_file_url VARCHAR2(200),
    CONSTRAINT fk_lab_patient FOREIGN KEY(patient_id) REFERENCES patient(patient_id),
    CONSTRAINT fk_lab_doctor FOREIGN KEY(doctor_id) REFERENCES doctor(doctor_id),
    CONSTRAINT fk_lab_test FOREIGN KEY(test_id) REFERENCES tests(test_id)
);

-- =========================
-- BED_BOOKING_APPOINTMENTS
-- =========================
CREATE TABLE bed_booking_appointments (
    bed_booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_appointment_id NUMBER,
    bed_id NUMBER,
    time_slot_id NUMBER,
    status VARCHAR2(20),
    CONSTRAINT fk_bed_booking_appointment FOREIGN KEY(doctor_appointment_id) REFERENCES doctors_appointments(appointment_id),
    CONSTRAINT fk_bed_booking_bed FOREIGN KEY(bed_id) REFERENCES beds(bed_id)
);

-- =========================
-- PRESCRIPTION
-- =========================
CREATE TABLE prescription (
    prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id NUMBER,
    date_issued DATE,
    chief_complaints VARCHAR2(400),
    investigations VARCHAR2(400),
    required_tests VARCHAR2(400),
    diagnosis VARCHAR2(400),
    history VARCHAR2(400),
    instructions VARCHAR2(400),
    visit_again_at DATE,
    CONSTRAINT fk_prescription_appointment FOREIGN KEY(appointment_id) REFERENCES doctors_appointments(appointment_id)
);

-- =========================
-- MEDICATIONS
-- =========================
CREATE TABLE medications (
    medication_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_name VARCHAR2(100),
    duration VARCHAR2(50),
    dosage VARCHAR2(50)
);

-- =========================
-- PRESCRIBED_MED
-- =========================
CREATE TABLE prescribed_med (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id NUMBER,
    medication_id NUMBER,
    CONSTRAINT fk_prescribed_prescription FOREIGN KEY(prescription_id) REFERENCES prescription(prescription_id),
    CONSTRAINT fk_prescribed_med FOREIGN KEY(medication_id) REFERENCES medications(medication_id)
);

-- =========================
-- HOSPITAL_BRANCHES
-- =========================
CREATE TABLE hospital_branches (
    branch_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER,
    name VARCHAR2(100),
    address VARCHAR2(200),
    established_date DATE
);

-- =========================
-- BRANCH_CONTACTS
-- =========================
CREATE TABLE branch_contacts (
    contact_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER,
    branch_id NUMBER,
    contact_no VARCHAR2(20),
    type VARCHAR2(50),
    CONSTRAINT fk_branch_contact_branch FOREIGN KEY(branch_id) REFERENCES hospital_branches(branch_id)
);

